spring:
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      maxIdle: 5
      maxTotal: 20
      testOnReturn: true
      testOnBorrow: true
      testWhileIdle: true
    database: 0
    ssl: false
    password: asdfcsafd.
    lettuce:
      pool:
        min-idle: 0
        max-active: 8
        max-wait: 1000ms
        shutdown-timeout: 100ms

  cache:
    type: redis
    redis:
      # 缓存空值，解决缓存穿透问题
      cache-null-values: true
      use-key-prefix: true
      # 设置缓存过期时间
      time-to-live: 3600000
